# Generated by Django 5.2.3 on 2025-06-26 23:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Categoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255, verbose_name="Nome da Loja")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL da Loja",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL do Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Marca"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Usuário"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "role",
                    models.BooleanField(
                        default=False, verbose_name="É Administrador/Gerente"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Produto"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "imagem_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL da Imagem",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.marca",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ProdutoIndicado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome_produto",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Produto Indicado"
                    ),
                ),
                (
                    "descricao_produto",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Produto"
                    ),
                ),
                (
                    "url_imagem",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL da Imagem",
                    ),
                ),
                ("motivacao", models.TextField(verbose_name="Motivação da Indicação")),
                (
                    "data_indicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Indicação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=50,
                        verbose_name="Status da Indicação",
                    ),
                ),
                (
                    "produto_existente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.produto",
                        verbose_name="Produto Existente Relacionado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usuario",
                        verbose_name="Usuário Indicador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto Indicado",
                "verbose_name_plural": "Produtos Indicados",
                "ordering": ["status", "-data_indicacao"],
            },
        ),
        migrations.CreateModel(
            name="ListaCompra",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome da Lista"),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada Em"),
                ),
                (
                    "finalizada",
                    models.BooleanField(default=False, verbose_name="Finalizada"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usuario",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Compra",
                "verbose_name_plural": "Listas de Compras",
                "ordering": ["finalizada", "-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemComprado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "preco_pago",
                    models.IntegerField(
                        verbose_name="Preço Pago (em centavos ou similar)"
                    ),
                ),
                ("data_compra", models.DateField(verbose_name="Data da Compra")),
                (
                    "loja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.loja",
                        verbose_name="Loja",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usuario",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Comprado",
                "verbose_name_plural": "Itens Comprados",
                "ordering": ["-data_compra"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField(verbose_name="Texto do Comentário")),
                (
                    "nota",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nota (1 a 5)",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Comentário"
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.loja",
                        verbose_name="Loja",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usuario",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "data_captura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Captura"
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.loja",
                        verbose_name="Loja",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Ofertas",
                "ordering": ["-data_captura"],
                "unique_together": {("produto", "loja", "data_captura")},
            },
        ),
        migrations.CreateModel(
            name="ItemLista",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "item_comprado",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.itemcomprado",
                        verbose_name="Item Comprado Associado",
                    ),
                ),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.listacompra",
                        verbose_name="Lista de Compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Lista",
                "verbose_name_plural": "Itens da Lista",
                "ordering": ["lista", "produto__nome"],
                "unique_together": {("lista", "produto")},
            },
        ),
    ]
