# Generated by Django 5.2.3 on 2025-06-27 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="adicionado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.usuario",
                verbose_name="Adicionado Por",
            ),
        ),
    ]
