# Generated by Django 5.2.3 on 2025-06-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0003_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Os grupos aos quais este usuário pertence. Um usuário obterá todas as permissões concedidas a cada um de seus grupos.",
                related_name="core_usuario_set",
                related_query_name="usuario",
                to="auth.group",
                verbose_name="Grupos",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissões específicas para este usuário.",
                related_name="core_usuario_permissions",
                related_query_name="usuario_permission",
                to="auth.permission",
                verbose_name="Permissões de Usuário",
            ),
        ),
    ]
