# Generated by Django 5.2.3 on 2025-07-14 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_alter_usuario_groups_alter_usuario_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="role",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="loja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comentarios",
                to="core.loja",
                verbose_name="Loja",
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="nota",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Nota (1 a 5)",
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comentarios",
                to="core.produto",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="itemcomprado",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="itemcomprado",
            name="preco_pago",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço Pago"
            ),
        ),
        migrations.AlterField(
            model_name="itemlista",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="itemlista",
            name="lista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.listacompra",
                verbose_name="Lista de Compra",
            ),
        ),
        migrations.AlterField(
            model_name="itemlista",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="listacompra",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="listacompra",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listas_de_compra",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="logo_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL do Logo"
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="nome",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nome da Loja"
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL da Loja"
            ),
        ),
        migrations.AlterField(
            model_name="marca",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="loja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ofertas",
                to="core.loja",
                verbose_name="Loja",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ofertas",
                to="core.produto",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL da Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="produtoindicado",
            name="descricao_produto",
            field=models.TextField(blank=True, verbose_name="Descrição do Produto"),
        ),
        migrations.AlterField(
            model_name="produtoindicado",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produtoindicado",
            name="motivacao",
            field=models.TextField(blank=True, verbose_name="Motivação da Indicação"),
        ),
        migrations.AlterField(
            model_name="produtoindicado",
            name="url_imagem",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL da Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Endereço de e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
