# Generated by Django 5.2.3 on 2025-07-13 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_usuario_groups_alter_usuario_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
