# Generated by Django 5.2.3 on 2025-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_usuario_role_alter_categoria_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
    ]
